name: Main

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run:  docker build -t joke-front .

      - name: Save image as archive
        run:  docker save joke-front -o ${{ vars.ARCHIVE_NAME }}

      - name: Checkout archive
        run: ls -lh ${{ vars.ARCHIVE_NAME }}

      - name: Set archive permissions
        run: chmod 644 ${{ vars.ARCHIVE_NAME }}