name: Main

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu:20.04.6
    steps:
      - uses: actions/checkout@v4
      - name: status
        run: echo "checkout was finished with success"
        shell: bash